import { z } from "zod";

export const SurveillanceCameraConfigSchema = z.object({
  id: z.string(),
  file_name: z.string(),
  location: z.string(),
  status: z.string(),
  system_mode: z.enum(["enforcement_mode", "traffic_management_mode"]),
  source: z.string(),
  stream_url: z.string(),
  video_url: z.string(),
  address: z.string(),
  location_link: z.string().nullable().optional(),
  mode_label: z.string().optional(),
  frame_skip: z.number().int().nullable().optional(),
  resolution: z.tuple([z.number().int(), z.number().int()]).nullable().optional(),
  fps_limit: z.number().nullable().optional(),
  ocr_enabled: z.boolean().nullable().optional(),
  ocr_debug: z.boolean().nullable().optional(),
  intersection_id: z.string().nullable().optional(),
  lanes: z.array(z.string()).optional().default([]),
  roi_config_path: z.string().nullable().optional(),
  confidence_threshold: z.number().nullable().optional(),
  plate_confidence_threshold: z.number().nullable().optional(),
  char_confidence_threshold: z.number().nullable().optional(),
  helmet_confidence_threshold: z.number().nullable().optional(),
  overspeed_threshold_kmh: z.number().nullable().optional(),
  line1_y: z.number().nullable().optional(),
  line2_y: z.number().nullable().optional(),
  line_distance_meters: z.number().nullable().optional(),
  line_tolerance_pixels: z.number().int().nullable().optional(),
  helmet_stability_frames: z.number().int().nullable().optional(),
  stop_speed_threshold_px: z.number().nullable().optional(),
  stop_frames_threshold: z.number().int().nullable().optional(),
  stop_line_distance_px: z.number().nullable().optional(),
  min_green_time: z.number().nullable().optional(),
  max_green_time: z.number().nullable().optional(),
  yellow_time: z.number().nullable().optional(),
  priority_queue_weight: z.number().nullable().optional(),
  priority_wait_weight: z.number().nullable().optional(),
  fairness_weight: z.number().nullable().optional(),
  max_priority_score: z.number().nullable().optional(),
  initial_active_lane: z.string().nullable().optional(),
});

export type SurveillanceCameraConfig = z.infer<typeof SurveillanceCameraConfigSchema>;
