import { z } from 'zod';

export const ViolationLogSchema = z.object({
  id: z.string(),
  title: z.string(),
  driverName: z.string(),
  age: z.number(),
  dob: z.string(),
  bloodGroup: z.string(),
  licensePlate: z.string(),
  tempAddress: z.string(),
  permAddress: z.string(),
  timestamp: z.string(),
  locationLink: z.string(),
  screenshot1Url: z.string(),
  screenshot2Url: z.string(),
  screenshot3Url: z.string(),
  videoUrl: z.string(),
  description: z.string(),
  verified: z.boolean(),
  cameraId: z.string().optional(),
  cameraLocation: z.string().optional(),
  cameraLocationLink: z.string().optional(),
  evidenceProvider: z.string().optional(),
  evidenceClipUrl: z.string().optional(),
  sourceVideoUrl: z.string().optional(),
  ownerName: z.string().optional(),
  ownerAddress: z.string().optional(),
  ownerContactNumber: z.string().optional(),
  vehicleColor: z.string().optional(),
  registrationDate: z.string().optional(),
  isMockData: z.boolean().optional(),
});

export type ViolationLog = z.infer<typeof ViolationLogSchema>;
